package com.decms.admin.service;

import com.decms.admin.dto.AuditReportResponse;
import org.springframework.stereotype.Component;

import java.time.format.DateTimeFormatter;

/**
 * HtmlReportFormatter
 *
 * Concrete implementation of ReportFormatter — produces
 * a self-contained styled HTML audit report.
 *
 * Demonstrates DIP (Khizer): this is the LOW-LEVEL module.
 * ReportService depends on the interface, not this class.
 */
@Component("htmlReportFormatter")
public class HtmlReportFormatter implements ReportFormatter {

    private static final DateTimeFormatter FMT =
            DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    @Override
    public String format(AuditReportResponse report) {
        StringBuilder html = new StringBuilder();

        html.append("<!DOCTYPE html><html lang='en'><head>")
            .append("<meta charset='UTF-8'>")
            .append("<title>Audit Report — Case ").append(esc(report.getCaseId())).append("</title>")
            .append("<style>")
            .append("body{font-family:Arial,sans-serif;margin:40px;color:#222;background:#fff;}")
            .append("h1{color:#1a3a5c;border-bottom:2px solid #1a3a5c;padding-bottom:8px;}")
            .append("h2{color:#2c5f8a;margin-top:32px;}")
            .append(".meta{background:#f0f4f8;padding:16px;border-radius:6px;margin:16px 0;}")
            .append(".meta p{margin:4px 0;font-size:14px;}")
            .append(".stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0;}")
            .append(".stat{background:#1a3a5c;color:#fff;padding:20px;border-radius:8px;text-align:center;}")
            .append(".stat .num{font-size:36px;font-weight:bold;}")
            .append(".stat .lbl{font-size:12px;opacity:0.85;margin-top:4px;}")
            .append(".warn{background:#fff3cd;border:1px solid #ffc107;padding:12px 16px;border-radius:6px;margin:8px 0;}")
            .append("table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px;}")
            .append("th{background:#1a3a5c;color:#fff;padding:10px 12px;text-align:left;}")
            .append("td{padding:8px 12px;border-bottom:1px solid #e0e0e0;}")
            .append("tr:hover td{background:#f5f8ff;}")
            .append(".badge{padding:3px 8px;border-radius:12px;font-size:11px;font-weight:bold;}")
            .append(".sealed{background:#e3f2fd;color:#1565c0;}")
            .append(".verified{background:#e8f5e9;color:#2e7d32;}")
            .append(".analyzed{background:#fff8e1;color:#f57f17;}")
            .append(".archived{background:#f3e5f5;color:#6a1b9a;}")
            .append(".suspicious{background:#ffebee;color:#c62828;}")
            .append(".footer{margin-top:48px;font-size:12px;color:#888;border-top:1px solid #e0e0e0;padding-top:12px;}")
            .append("</style></head><body>");

        // Header
        html.append("<h1>Digital Evidence Audit Report</h1>");
        html.append("<div class='meta'>")
            .append("<p><strong>Case ID:</strong> ").append(esc(report.getCaseId())).append("</p>")
            .append("<p><strong>Generated By:</strong> ").append(esc(report.getGeneratedByName())).append("</p>")
            .append("<p><strong>Generated At:</strong> ")
            .append(report.getGeneratedAt() != null ? report.getGeneratedAt().format(FMT) : "—")
            .append("</p>")
            .append("<p><strong>Report ID:</strong> ").append(esc(report.getReportId())).append("</p>")
            .append("</div>");

        // Summary stats
        html.append("<div class='stats'>")
            .append(stat(String.valueOf(report.getTotalEvidenceItems()), "Evidence Items"))
            .append(stat(String.valueOf(report.getTotalCustodyEvents()), "Custody Events"))
            .append(stat(String.valueOf(report.getVerifiedCount()), "Verified Items"))
            .append(stat(String.valueOf(report.getTamperingAlertCount()), "Tampering Alerts"))
            .append(stat(String.valueOf(report.getPendingAccessRequests()), "Pending Requests"))
            .append("</div>");

        // Tampering warning
        if (report.getTamperingAlertCount() > 0) {
            html.append("<div class='warn'>")
                .append("&#9888; <strong>WARNING:</strong> ")
                .append(report.getTamperingAlertCount())
                .append(" tampering alert(s) detected. Immediate review required.")
                .append("</div>");
        }

        // Evidence table
        html.append("<h2>Evidence Items</h2>");
        if (report.getEvidenceItems() == null || report.getEvidenceItems().isEmpty()) {
            html.append("<p>No evidence items found for this case.</p>");
        } else {
            html.append("<table><tr>")
                .append("<th>Evidence ID</th><th>Description</th><th>Type</th>")
                .append("<th>Status</th><th>Uploaded By</th><th>Upload Time</th>")
                .append("<th>SHA-256 Hash</th><th>Events</th></tr>");
            for (AuditReportResponse.EvidenceRow row : report.getEvidenceItems()) {
                html.append("<tr>")
                    .append("<td>").append(esc(row.getEvidenceId())).append("</td>")
                    .append("<td>").append(esc(row.getDescription())).append("</td>")
                    .append("<td>").append(esc(row.getFileType())).append("</td>")
                    .append("<td><span class='badge ").append(row.getStatus().toLowerCase()).append("'>")
                    .append(esc(row.getStatus())).append("</span></td>")
                    .append("<td>").append(esc(row.getUploadedBy())).append("</td>")
                    .append("<td>").append(esc(row.getUploadTimestamp())).append("</td>")
                    .append("<td style='font-family:monospace;font-size:11px;'>")
                    .append(esc(row.getHashValue())).append("</td>")
                    .append("<td style='text-align:center;'>").append(row.getCustodyEventCount()).append("</td>")
                    .append("</tr>");
            }
            html.append("</table>");
        }

        // Custody timeline
        html.append("<h2>Chain-of-Custody Timeline</h2>");
        if (report.getCustodyTimeline() == null || report.getCustodyTimeline().isEmpty()) {
            html.append("<p>No custody events recorded for this case.</p>");
        } else {
            html.append("<table><tr>")
                .append("<th>Timestamp</th><th>Evidence ID</th><th>Actor</th>")
                .append("<th>Role</th><th>Action</th><th>IP Address</th><th>Flag</th></tr>");
            for (AuditReportResponse.CustodyEventRow row : report.getCustodyTimeline()) {
                String flag = row.isSuspicious()
                        ? "<span class='badge suspicious'>&#9888; SUSPICIOUS</span>"
                        : "<span style='color:#aaa;'>—</span>";
                html.append("<tr>")
                    .append("<td>").append(esc(row.getTimestamp())).append("</td>")
                    .append("<td>").append(esc(row.getEvidenceId())).append("</td>")
                    .append("<td>").append(esc(row.getActorName())).append("</td>")
                    .append("<td>").append(esc(row.getActorRole())).append("</td>")
                    .append("<td>").append(esc(row.getActionType())).append("</td>")
                    .append("<td>").append(esc(row.getIpAddress())).append("</td>")
                    .append("<td>").append(flag).append("</td>")
                    .append("</tr>");
            }
            html.append("</table>");
        }

        html.append("<div class='footer'>Generated by DECMS — Digital Evidence &amp; Chain-of-Custody Management System.</div>");
        html.append("</body></html>");
        return html.toString();
    }

    @Override
    public String getFormatName() { return "HTML"; }

    @Override
    public String getContentType() { return "text/html"; }

    private String stat(String number, String label) {
        return "<div class='stat'><div class='num'>" + number + "</div><div class='lbl'>" + label + "</div></div>";
    }

    private String esc(String value) {
        if (value == null) return "—";
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
