package com.decms.admin.service;

import com.decms.admin.dto.AuditReportResponse;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.util.Base64;

/**
 * PdfReportFormatter
 *
 * Concrete implementation of ReportFormatter — produces
 * a PDF audit report using iText 8.
 *
 * Demonstrates DIP (Khizer): LOW-LEVEL module.
 * ReportService depends on the interface, not this class.
 * Spring injects this when format = "PDF".
 *
 * PDF bytes are Base64-encoded for storage in DB.
 * AdminController decodes them on download.
 */
@Component("pdfReportFormatter")
public class PdfReportFormatter implements ReportFormatter {

    private static final DeviceRgb NAVY  = new DeviceRgb(26, 58, 92);
    private static final DeviceRgb WHITE = new DeviceRgb(255, 255, 255);
    private static final DeviceRgb LIGHT = new DeviceRgb(240, 244, 248);

    @Override
    public String format(AuditReportResponse report) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {

            PdfDocument pdfDoc = new PdfDocument(new PdfWriter(baos));
            Document document  = new Document(pdfDoc);
            document.setMargins(40, 40, 40, 40);

            // Title
            document.add(new Paragraph("Digital Evidence Audit Report")
                    .setFontSize(22).setBold().setFontColor(NAVY)
                    .setTextAlignment(TextAlignment.CENTER));

            document.add(new Paragraph("Case ID: " + safe(report.getCaseId()))
                    .setFontSize(12).setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));

            // Metadata
            document.add(new Paragraph("\nReport Information")
                    .setFontSize(14).setBold().setFontColor(NAVY));

            Table meta = new Table(UnitValue.createPercentArray(new float[]{30, 70}))
                    .setWidth(UnitValue.createPercentValue(100));
            addMeta(meta, "Generated By", safe(report.getGeneratedByName()));
            addMeta(meta, "Generated At",
                    report.getGeneratedAt() != null ? report.getGeneratedAt().toString() : "—");
            addMeta(meta, "Report ID", safe(report.getReportId()));
            document.add(meta);

            // Summary stats
            document.add(new Paragraph("\nSummary Statistics")
                    .setFontSize(14).setBold().setFontColor(NAVY));

            Table stats = new Table(UnitValue.createPercentArray(new float[]{1,1,1,1,1}))
                    .setWidth(UnitValue.createPercentValue(100));

            String[] labels = {"Evidence Items","Custody Events","Verified","Alerts","Pending"};
            String[] values = {
                String.valueOf(report.getTotalEvidenceItems()),
                String.valueOf(report.getTotalCustodyEvents()),
                String.valueOf(report.getVerifiedCount()),
                String.valueOf(report.getTamperingAlertCount()),
                String.valueOf(report.getPendingAccessRequests())
            };
            for (int i = 0; i < labels.length; i++) {
                stats.addCell(new Cell()
                        .setBackgroundColor(NAVY).setTextAlignment(TextAlignment.CENTER)
                        .add(new Paragraph(values[i]).setFontColor(WHITE).setFontSize(20).setBold())
                        .add(new Paragraph(labels[i]).setFontColor(WHITE).setFontSize(9)));
            }
            document.add(stats);

            // Tampering warning
            if (report.getTamperingAlertCount() > 0) {
                document.add(new Paragraph(
                        "WARNING: " + report.getTamperingAlertCount() +
                        " tampering alert(s) detected. Immediate review required.")
                        .setBold().setFontSize(11).setMarginTop(12));
            }

            // Evidence table
            document.add(new Paragraph("\nEvidence Items")
                    .setFontSize(14).setBold().setFontColor(NAVY));

            if (report.getEvidenceItems() != null && !report.getEvidenceItems().isEmpty()) {
                Table ev = new Table(UnitValue.createPercentArray(new float[]{20,20,10,12,15,15,8}))
                        .setWidth(UnitValue.createPercentValue(100)).setFontSize(9);
                for (String h : new String[]{"Evidence ID","Description","Type","Status","Uploaded By","Upload Time","Events"}) {
                    ev.addHeaderCell(new Cell().setBackgroundColor(NAVY)
                            .add(new Paragraph(h).setFontColor(WHITE).setBold()));
                }
                for (AuditReportResponse.EvidenceRow row : report.getEvidenceItems()) {
                    ev.addCell(safe(row.getEvidenceId()));
                    ev.addCell(safe(row.getDescription()));
                    ev.addCell(safe(row.getFileType()));
                    ev.addCell(safe(row.getStatus()));
                    ev.addCell(safe(row.getUploadedBy()));
                    ev.addCell(safe(row.getUploadTimestamp()));
                    ev.addCell(new Cell().setTextAlignment(TextAlignment.CENTER)
                            .add(new Paragraph(String.valueOf(row.getCustodyEventCount()))));
                }
                document.add(ev);
            }

            // Custody timeline
            document.add(new Paragraph("\nChain-of-Custody Timeline")
                    .setFontSize(14).setBold().setFontColor(NAVY));

            if (report.getCustodyTimeline() != null && !report.getCustodyTimeline().isEmpty()) {
                Table ct = new Table(UnitValue.createPercentArray(new float[]{18,18,14,14,12,14,10}))
                        .setWidth(UnitValue.createPercentValue(100)).setFontSize(9);
                for (String h : new String[]{"Timestamp","Evidence ID","Actor","Role","Action","IP Address","Flag"}) {
                    ct.addHeaderCell(new Cell().setBackgroundColor(NAVY)
                            .add(new Paragraph(h).setFontColor(WHITE).setBold()));
                }
                for (AuditReportResponse.CustodyEventRow row : report.getCustodyTimeline()) {
                    ct.addCell(safe(row.getTimestamp()));
                    ct.addCell(safe(row.getEvidenceId()));
                    ct.addCell(safe(row.getActorName()));
                    ct.addCell(safe(row.getActorRole()));
                    ct.addCell(safe(row.getActionType()));
                    ct.addCell(safe(row.getIpAddress()));
                    ct.addCell(new Cell().setTextAlignment(TextAlignment.CENTER)
                            .add(new Paragraph(row.isSuspicious() ? "SUSPICIOUS" : "—")
                                    .setFontColor(row.isSuspicious()
                                            ? ColorConstants.RED : ColorConstants.GRAY)));
                }
                document.add(ct);
            }

            // Footer
            document.add(new Paragraph(
                    "\nGenerated by DECMS — Digital Evidence & Chain-of-Custody Management System.")
                    .setFontSize(9).setFontColor(ColorConstants.GRAY).setMarginTop(24));

            document.close();
            return Base64.getEncoder().encodeToString(baos.toByteArray());

        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed: " + e.getMessage(), e);
        }
    }

    @Override
    public String getFormatName() { return "PDF"; }

    @Override
    public String getContentType() { return "application/pdf"; }

    private void addMeta(Table table, String label, String value) {
        table.addCell(new Cell().setBackgroundColor(LIGHT)
                .add(new Paragraph(label).setBold().setFontSize(10)));
        table.addCell(new Cell().add(new Paragraph(value).setFontSize(10)));
    }

    private String safe(String v) { return v != null ? v : "—"; }
}
